Test: In test_recorder.py, changed code to avoid a new AssertionError raised
by testfixtures 8.3.0.
